FROM 082388193175.dkr.ecr.us-east-1.amazonaws.com/awsfusionruntime-python311:uuid-python311-20251118-203652-107

WORKDIR /app/backend


COPY backend/requirements.txt .

RUN python3 -m pip install --no-cache-dir -r requirements.txt


COPY backend/ .

EXPOSE 8080

CMD ["python3", "-m", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]